// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddTodoController from "./add_todo_controller.js"
application.register("add-todo", AddTodoController)

import BlockController from "./block_controller.js"
application.register("block", BlockController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import GiveController from "./give_controller.js"
application.register("give", GiveController)

import AnswersController from "./answers_controller.js"
application.register("answers", AnswersController)

import TurbomodalsController from "./turbomodals_controller.js"
application.register("turbomodals", TurbomodalsController)

import EmojiPickerController from "./emoji_picker_controller.js"
application.register("emoji-picker", EmojiPickerController)

import ActiveStorageDragAndDrop from 'active_storage_drag_and_drop'
ActiveStorageDragAndDrop.start()
